initialCash = 1000

backtestStart = 2025-05-27T13:30:00
backtestEnd = 2025-05-30T20:00:00
backtestLowRisk = true
backtestHighRisk = true
backtestAllowance = false
backtestStrategy = true

recalibrate = false
# recalibrate every x minutes (1440 minutes = 1 day)
recalibrateFreq = 720
# recalibrate using x hours of historical data (720 hours = 30 days)
recalibrateHours = 24

shortLookback = 0
longLookback = 1
lowRisk = 0.01
highRisk = 0.10
allowance = .95
stopLoss = .90
fee = .00155

# BUY1, BUY2, BUY3, BUY4
buyStrategy = BUY3
# SELL1, SELL2, SELL3, SELL4, SELL5
sellStrategy = SELL4
# TICKER, TRADE, ORDER_BOOK, KLINE, BAR, QUOTE
dataFeed = BAR

# for securities, use comma separated stock symbols with no spaces, e.g. AAPL,GOOG,MSFT
securities = AAPL
# for fiatCurrencies, use comma separated fiatCurrencies with no spaces, e.g. USD,CAD. USD is required.
fiatCurrencies = USD
# for cryptocurrencies, use comma separated cryptocurrencies with no spaces, e.g. BTC,USDT,ETH
cryptoCurrencies = BTC
# ALPACA, ALPACA_SECURITY_TEST, ALPACA_CRYPTO_TEST, COINBASE, CEXIO, BINANCE, BINANCE_TEST, see com.jessethouin.quant.conf.Broker
broker = ALPACA